module.exports = {
  portrait:       require('./portrait.json'),
  landscape:      require('./landscape.json'),
  astro:          require('./astro.json'),
  wildlife:       require('./wildlife.json'),
  sports:         require('./sports.json'),
  macro:          require('./macro.json'),
  indoorlowlight: require('./indoorlowlight.json'),
  goldenhour:     require('./goldenhour.json'),
  street:         require('./street.json'),
  architecture:   require('./architecture.json'),
  event:          require('./event.json'),
  travel:         require('./travel.json'),
  food:           require('./food.json'),
  realestate:     require('./realestate.json'),
  automotive:     require('./automotive.json'),
  product:        require('./product.json'),
  concert:        require('./concert.json'),
  underwater:     require('./underwater.json'),
  drone:          require('./drone.json'),
  newborn:        require('./newborn.json'),
  fashion:        require('./fashion.json'),
};
